# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedTrajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.DecimalField(decimal_places=6, max_digits=15)),
                ('roll', models.DecimalField(decimal_places=6, max_digits=15)),
                ('u0_string', models.TextField()),
            ],
        ),
    ]
