# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crazyflie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedtrajectory',
            name='file_name',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solvedtrajectory',
            name='pitch',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='solvedtrajectory',
            name='roll',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='solvedtrajectory',
            name='u0_string',
            field=models.TextField(null=True),
        ),
    ]
